# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Run tests manually: pre-commit run --all-files
# Skip tests on linux: SKIP="pylint,check-yaml" git commit ...
# Skip tests on win10: set SKIP=pylint,check-yaml
#                      git commit ...
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
#    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff-format
        args: [--check]
      - id: ruff

#-   repo: https://github.com/psf/black
#    rev: 23.7.0
#    hooks:
#    -   id: black

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets

-   repo: https://github.com/codingjoe/relint.git
    rev: 3.1.0
    hooks:
    -   id: relint
        name: check for sensitive patterns
        args: []

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        require_serial: true

-   repo: https://github.com/jackdewinter/pymarkdown
    rev: 0.9.16
    hooks:
      - id: pymarkdown
        pass_filenames: false
        args:
          - -s
          - plugins.md013.heading_line_length=$#120
          - scan
          - -r
          - ./docs
