---
site_name: Fortimanager Template Sync
site_description: Supporting of Fortinet CLI template development and deployment
site_author: Viktor Kertesz
site_url: https://fortimanager-template-sync.github.io/

repo_name: viktorkertesz/fortimanager-template-sync
repo_url: https://github.com/viktorkertesz/fortimanager-template-sync

theme:
  name: material

extra_css:
  - extra.css

nav:
  - Home: README.md
  - GitHub Guide:
      - Developing templates: github_guide/github_workflow.md
      - Creating actions: github_guide/github_actions.md
  - User Guide:
      - Quick Start Guide: user_guide/quickstart.md
      - Installation: user_guide/installation.md
      - Repository Structure: user_guide/repository.md
      - Lab setup: user_guide/lab_setup.md
  - Developer Guide:
      - Lab setup: user_guide/lab_setup.md
  - Code Reference: reference/

plugins:
- search
- gen-files:
    scripts:
      - docs/gen_ref_pages.py
- mkdocstrings:
    handlers:
      python:
        paths: [ fortimanager_template_sync ]
        options:
          line_length: 120
          separate_signature: true
          show_signature_annotations: true
          signature_crossrefs: true
          # add __init__ args to class and ignore __init__ summary text
          merge_init_into_class: true
          docstring_options:
            ignore_init_summary: true
          members: true
          show_labels: true
          group_by_category: true
          parameter_headings: false

- section-index
- literate-nav

watch:
    - fortimanager_template_sync
