---
site_name: Fortimanager Template Sync
site_description: Supporting of Fortinet CLI template development and deployment
site_author: Viktor Kertesz
site_url: https://fortimanager-template-sync.github.io/

repo_name: realvitya/fortimanager-template-sync
repo_url: https://github.com/realvitya/fortimanager-template-sync

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.path  # insider
    - content.code.copy
    - content.code.select

copyright: Copyright &copy; 2024 Viktor Kertesz

extra_css:
  - extra.css

nav:
  - Home: README.md
  - User Guide:
      - Quick Start Guide: user_guide/quickstart.md
      - Installation: user_guide/installation.md
      - Lab Setup: user_guide/lab_setup.md
      - Repository Structure: user_guide/repository.md
  - GitHub Guide:
      - github_guide/index.md
      - Repository Settings: github_guide/github_repository.md
      - Developing Templates: github_guide/github_workflow.md
      - Creating Actions: github_guide/github_actions.md
  - Developer Guide:
      - developer_guide/index.md
  - Code Reference: reference/

plugins:
- search
- gen-files:
    scripts:
      - docs/gen_ref_pages.py
- mkdocstrings:
    handlers:
      python:
        paths: [ fortimanager_template_sync ]
        options:
          line_length: 120
          separate_signature: true
          show_signature_annotations: true
          signature_crossrefs: true
          # add __init__ args to class and ignore __init__ summary text
          merge_init_into_class: true
          docstring_options:
            ignore_init_summary: true
          members: true
          show_labels: true
          group_by_category: true
          parameter_headings: false
          filters:
            - "!__"

- section-index
- literate-nav

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 1
      separator: "_"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - tables

watch:
    - fortimanager_template_sync
